package com.pb.constants;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class ResponseMessageConstant {
    
    public static final String USER_NOT_FOUND = "USER NOT FOUND";
    public static final String USER_REGISTRATION_SUCCESSFULLY = "USER REGISTRATION SUCCESSFULLY";
    public static final String USER_UPDATED_SUCCESSFULLY = "USER UPDATED SUCCESSFULLY";
    public static final String USER_DELETED_SUCCESSFULLY = "USER DELETED SUCCESSFULLY";
    public static final String EMAIL_ALREADY_EXIST = "EMAIL ID ALREADY EXIST";
    public static final String USERNAME_ALREADY_EXIST = "USERNAME ALREADY EXIST";
    public static final String PLEASE_PROVIDE_ROLE = "PLEASE PROVIDE ROLE";
    public static final String USERS_FETCHED_SUCCESSFULLY = "USERS FETCH SUCCESSFULLY";
    public static final String USER_FETCHED_SUCCESSFULLY = "USER FETCH SUCCESSFULLY";
    public static final String LINK_SENT_SUCCESSFULLY = "EMAIL SENT SUCCESSFULLY";
    public static final String EMAIL_VERIFIED_SUCCESSFULLY = "EMAIL VERIFIED SUCCESSFULLY";
    public static final String INVALID_JWT_TOKEN = "INVALID JWT TOKEN";
    public static final String ADMIN_LOGIN_SUCCESSFULLY = "YOU HAVE LOGIN SUCCESSFULLY";
    public static final String ADMIN_CANT_LOGIN = "YOUR ACCOUNT IS DEACTIVATED.PLEASE CONTACT ADMINISTRATION.";
    public static final String SOMETHING_WENT_WRONG = "SOMETHING WENT WRONG";
    public static final String USER_STATUS_CHANGE_SUCCESSFULLY = "USER STATUS CHANGE SUCCESSFULLY";
    public static final String USER_STATUS_CANT_BE_CHANGED = "USER STATUS CANT BE CHANGED AS THERE IS ONLY ONE ADMIN EXIST";
    
    public static final String CONTENT_NOT_FOUND = "CONTENT NOT FOUND";
    public static final String CONTENT_FETCHED_SUCCESSFULLY = "CONTENT FETCH SUCCESSFULLY";
    public static final String CONTENT_DELETED_SUCCESSFULLY = "CONTENT DELETED SUCCESSFULLY";
    public static final String CONTENT_UPDATED_SUCCESSFULLY = "CONTENT UPDATED SUCCESSFULLY";
    public static final String CONTENT_ADDED_SUCCESSFULLY = "CONTENT ADDED SUCCESSFULLY";
    public static final String CONTENT_STATUS_CHANGE_SUCCESSFULLY = "CONTENT STATUS CHANGE SUCCESSFULLY";

    public static final String UN_REPRESENTATIVE_FETCHED_SUCCESSFULLY = "UN-REPRESENTATIVE FETCH SUCCESSFULLY";
    public static final String UN_REPRESENTATIVE_UPDATED_SUCCESSFULLY = "UN-REPRESENTATIVE UPDATED SUCCESSFULLY";
    public static final String UN_REPRESENTATIVE_ADDED_SUCCESSFULLY = "UN-REPRESENTATIVE ADDED SUCCESSFULLY";
    public static final String UN_REPRESENTATIVE_FETCH_SUCCESSFULLY = "UN-REPRESENTATIVE FETCHED SUCCESSFULLY";
    
    public static final String COUNTRY_FETCHED_SUCCESSFULLY = "COUNTRY FETCH SUCCESSFULLY";
    public static final String TIMEZONE_FETCHED_SUCCESSFULLY = "TIMEZONE FETCH SUCCESSFULLY";
    public static final String COUNTRY_NOT_FOUND = "COUNTRY NOT FOUND";
    
    public static final String PAGE_NAME_ALREADY_EXIST = "PAGE NAME ALREADY EXIST";
    public static final String UN_REPRESENTATIVE_ALREADY_EXISTS = "UN REPRESENTATIVE ALREADY EXISTS";
    
    public static final String BANNER_ADDED_SUCCESSFULLY = "BANNER ADDED SUCCESSFULLY";
    public static final String BANNER_UPDATED_SUCCESSFULLY = "BANNER UPDATED SUCCESSFULLY";
    public static final String BANNER_FETCH_SUCCESSFULLY = "BANNER FETCH SUCCESSFULLY";
    public static final String BANNER_DELETED_SUCCESSFULLY = "BANNER DELETED SUCCESSFULLY";
    public static final String BANNER_NOT_FOUND = "BANNER NOT FOUND";
    public static final String BANNER_ALREADY_EXIST = "BANNER ALREADY EXISTS WITH THIS NAME";
    public static final String PLAN_ADDED_SUCCESSFULLY = "PLAN ADDED SUCCESSFULLY";
    public static final String PLAN_FETCHED_SUCCESSFULLY = "PLAN FETCHED SUCCESSFULLY";
    public static final String PLAN_DELETED_SUCCESSFULLY = "PLAN DELETED SUCCESSFULLY";
    public static final String PLAN_NOT_FOUND = "PLAN NOT FOUND";
    public static final String PLAN_UPDATED_SUCCESSFULLY = "PLAN UPDATED SUCCESSFULLY";
    public static final String PERMISSIONS_FETCHED_SUCCESSFULLY = "PERMISSIONS FETCHED SUCCESSFULLY";
    public static final String PLAN_PERMISSIONS_FETCHED_SUCCESSFULLY = "PLAN PERMISSIONS UPDATED SUCCESSFULLY";
    public static final String PLAN_STATUS_CHANGED_SUCCESSFULLY = "PLAN STATUS CHANGED SUCCESSFULLY";
    public static final String RETAILER_DELETED_SUCCESSFULLY = "RETAILER DELETED SUCCESSFULLY";
    public static final String RETAILER_NOT_FOUND = "RETAILER NOT FOUND";
    public static final String PLAN_ALREADY_EXISTS = "PLAN ALREADY EXISTS";
    public static final String OTP_SEND_SUCCESSFULLY = "OTP SEND SUCCESSFULLY";
    public static final String OTP_VERIFY_SUCCESSFULLY = "OTP VERIFY SUCCESSFULLY";
    public static final String INVALID_OTP = "INVALID OTP";
    public static final String OTP_EXPIRED = "OTP EXPIRED";
    public static final String PASSWORD_AND_CONFIRM_PASSWORD_SAME = "PASSWORD AND CONFIRM PASSWORD MUST BE SAME";
    
    public static final String PASSWORD_CHANGED_SUCCESSFULLY = "PASSWORD CHANGED SUCCESSFULLY";

    public static final String DEPARTMENT_ALREADY_EXISTS = "DEPARTMENT ALREADY EXIST";
    public static final String DEPARTMENT_NOT_FOUND = "DEPARTMENT NOT FOUND";
    
    public static final String DEPARTMENT_ADDED_SUCCESSFULLY = "DEPARTMENT ADDED SUCCESSFULLY";
    public static final String DEPARTMENT_UPDATED_SUCCESSFULLY = "DEPARTMENT UPDATED SUCCESSFULLY";
    
    public static final String DEPARTMENT_FETCH_SUCCESSFULLY = "DEPARTMENT FETCH SUCCESSFULLY";
    public static final String DEPARTMENT_DELETED_SUCCESSFULLY = "DEPARTMENT DELETED SUCCESSFULLY";
    public static final String DEPARTMENT_CANT_BE_DELETED = "Please delete all category of this department";
    public static final String DEPARTMENT_STATUS_CHANGED_SUCCESSFULLY = "DEPARTMENT STATUS CHANGED SUCCESSFULLY";
    public static final String DEPARTMENT_STATUS_CANT_BE_CHANGED = "Please delete all categories of this department before making it Inactive";
    
    
    public static final String CATEGORY_ALREADY_EXISTS = "CATEGORY ALREADY EXIST";
    public static final String CATEGORY_NOT_FOUND = "CATEGORY NOT FOUND";
    
    public static final String CATEGORY_ADDED_SUCCESSFULLY = "CATEGORY ADDED SUCCESSFULLY";
    public static final String CATEGORY_UPDATED_SUCCESSFULLY = "CATEGORY UPDATED SUCCESSFULLY";
    
    public static final String CATEGORY_FETCH_SUCCESSFULLY = "CATEGORY FETCH SUCCESSFULLY";
    public static final String CATEGORY_DELETED_SUCCESSFULLY = "CATEGORY DELETED SUCCESSFULLY";
    public static final String CATEGORY_STATUS_CHANGED_SUCCESSFULLY = "CATEGORY STATUS CHANGED SUCCESSFULLY";




    public static final String SUB_CATEGORY_ALREADY_EXISTS = "SUB-CATEGORY ALREADY EXIST";
    public static final String SUB_CATEGORY_NOT_FOUND = "SUB-CATEGORY NOT FOUND";
    public static final String SUB_CATEGORY_ADDED_SUCCESSFULLY = "SUB-CATEGORY ADDED SUCCESSFULLY";
    public static final String SUB_CATEGORY_UPDATED_SUCCESSFULLY = "SUB-CATEGORY UPDATED SUCCESSFULLY";
    public static final String SUB_CATEGORY_FETCH_SUCCESSFULLY = "SUB-CATEGORY FETCH SUCCESSFULLY";
    public static final String SUB_CATEGORY_DELETED_SUCCESSFULLY = "SUB-CATEGORY DELETED SUCCESSFULLY";
    public static final String SUB_CATEGORY_STATUS_CHANGED_SUCCESSFULLY = "SUB-CATEGORY STATUS CHANGED SUCCESSFULLY";


    public static final String PROFILE_UPDATED_SUCCESSFULLY = "USER PROFILE UPDATED SUCCESSFULLY";

    public static final String PRODUCT_ADDED_SUCCESSFULLY = "PRODUCT ADDED SUCCESSFULLY";
    public static final String PRODUCT_FETCH_SUCCESSFULLY = "PRODUCT FETCH SUCCESSFULLY";
    public static final String PRODUCT_DELETED_SUCCESSFULLY = "PRODUCT DELETED SUCCESSFULLY";
    public static final String PRODUCT_NOT_FOUND = "PRODUCT NOT FOUND";
    public static final String SUBSCRIPTION_CANCELLED_AND_BIND = "SUBSCRIPTION CANCELLED AND BIND SUCCESSFULLY";
    public static final String SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION NOT FOUND";
    public static final String CUSTOMER_PAYMENT_SUBSCRIPTION_CREATED = "CUSTOMER, PAYMENT AND SUBSCRIPTION CREATED SUCCESSFULLY";
    public static final String PAYMENT_RETRIEVED_SUCCESSFULLY = "PAYMENT RETRIEVED SUCCESSFULLY";
    public static final String CUSTOMER_RETRIEVED_SUCCESSFULLY = "CUSTOMER RETRIEVED SUCCESSFULLY";
    public static final String PAYMENT_METHOD_NOT_FOUND = "NO PAYMENT METHOD ATTACHED WITH CUSTOMER";
    public static final String PRICE_NOT_FOUND = "PRICE NOT FOUND";
    public static final String CUSTOMER_CANT_BE_CREATED = "CUSTOMER CANT BE CREATED";
    public static final String CUSTOMER_NOT_FOUND = "CUSTOMER NOT FOUND";
}
