name: Build and Deploy Docker Container

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build --file Dockerfile --tag ghcr.io/${{ github.actor }}/pribrr-backend:latest .

      - name: Log in to Ubuntu Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MASTER }}
          username: ${{ secrets.SSH_USER_MASTER }}
          key: ${{ secrets.SSH_KEY_MASTER }}
          script: |
            docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.DOCKER_TOKEN }}"
            docker pull ghcr.io/${{ github.actor }}/pribrr-backend:latest
            cd /var/www/html
            docker-compose down
            docker-compose up -d --force-recreate
