name: Build and Deploy Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build --file Dockerfile --tag ghcr.io/${{ github.actor }}/pribrr-backend:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Ubuntu Server via SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_MASTER }}
          ssh-config: "StrictHostKeyChecking no"

      - name: Deploy to Ubuntu Server
        run: |
         ssh ubuntu@107.21.202.114 << 'EOF'
          docker login ghcr.io -u '${{ github.actor }}' -p '${{ secrets.DOCKER_TOKEN }}'
          docker pull ghcr.io/${{ github.actor }}/backend-java-app:latest
          docker-compose -f /var/www/html/docker-compose.yml down
          docker-compose -f /var/www/html/docker-compose.yml up -d
         EOF
