name: Build and Deploy Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build --file Dockerfile --tag ghcr.io/${{ github.actor }}/pribrr-backend:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Ubuntu Server via SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_MASTER }}
          ssh-config: "StrictHostKeyChecking no"

      - name: Deploy Stage Build
        run: |
          ssh stage 'echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin'
          ssh stage 'cd /var/www/html/api; docker system prune -f; docker-compose pull; docker-compose up -d --force-recreate'
