name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push myapp

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MASTER }}
          username: ${{ secrets.SSH_USER_MASTER }}
          key: ${{ secrets.SSH_KEY_MASTER }}

      - name: Pull Docker image from Docker Hub
        run: docker pull myapp

      - name: Stop existing container
        run: docker stop myapp || true

      - name: Remove existing container
        run: docker rm myapp || true

      - name: Run new container
        run: docker run -d --name myapp -p 80:80 myapp
